"""empty message

Revision ID: 157716b96b21
Revises: 33b8a933f733
Create Date: 2015-03-10 14:52:02.684461

"""

# revision identifiers, used by Alembic.
revision = '157716b96b21'
down_revision = '33b8a933f733'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'myprofile_first_name_key', 'myprofile', type_='unique')
    op.drop_constraint(u'myprofile_last_name_key', 'myprofile', type_='unique')
    op.drop_constraint(u'myprofile_nickname_key', 'myprofile', type_='unique')
    op.drop_column('myprofile', 'nickname')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myprofile', sa.Column('nickname', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.create_unique_constraint(u'myprofile_nickname_key', 'myprofile', ['nickname'])
    op.create_unique_constraint(u'myprofile_last_name_key', 'myprofile', ['last_name'])
    op.create_unique_constraint(u'myprofile_first_name_key', 'myprofile', ['first_name'])
    ### end Alembic commands ###
