"""empty message

Revision ID: 420b9f97c3e7
Revises: 157716b96b21
Create Date: 2015-03-10 14:55:03.301356

"""

# revision identifiers, used by Alembic.
revision = '420b9f97c3e7'
down_revision = '157716b96b21'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myprofile', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('myprofile', sa.Column('nickname', sa.String(length=80), nullable=True))
    op.create_index(op.f('ix_myprofile_email'), 'myprofile', ['email'], unique=True)
    op.create_unique_constraint(None, 'myprofile', ['nickname'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'myprofile', type_='unique')
    op.drop_index(op.f('ix_myprofile_email'), table_name='myprofile')
    op.drop_column('myprofile', 'nickname')
    op.drop_column('myprofile', 'email')
    ### end Alembic commands ###
