"""empty message

Revision ID: 5d24a6e8edd4
Revises: 734beb9e3bc6
Create Date: 2016-03-02 02:17:45.742408

"""

# revision identifiers, used by Alembic.
revision = '5d24a6e8edd4'
down_revision = '734beb9e3bc6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myprofile', sa.Column('password', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('myprofile', 'password')
    ### end Alembic commands ###
