"""empty message

Revision ID: 734beb9e3bc6
Revises: 900fe6bf60c0
Create Date: 2016-03-02 02:16:44.555530

"""

# revision identifiers, used by Alembic.
revision = '734beb9e3bc6'
down_revision = '900fe6bf60c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('myprofile', 'password')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myprofile', sa.Column('password', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    ### end Alembic commands ###
