"""empty message

Revision ID: 900fe6bf60c0
Revises: None
Create Date: 2016-03-02 02:16:10.675168

"""

# revision identifiers, used by Alembic.
revision = '900fe6bf60c0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
